.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. titcoin_qt test_titcoin_qt
clean: FORCE
	$(MAKE) -C .. titcoin_qt_clean test_titcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_titcoin_qt_check
titcoin-qt titcoin-qt.exe: FORCE
	 $(MAKE) -C .. titcoin_qt
